element-hq/compound-web

- .storybook/main.ts
- .storybook/preview.ts
- package.json
- src/styles/global.css
- yarn.lock
Requires https://github.com/vector-im/compound-design-tokens/pull/45
Fixes the issue raised by @t3chguy in https://github.com/vector-im/compound-web/pull/20
- Set correct storybook canvas bg color
- Add theme selector dropdown
> Set correct storybook canvas bg color

- .storybook/main.ts
- package.json
- vite.config.ts
When I started using compound, I figured that the output CSS was over 1Mb. This was due to the assets being inlined.
This PR opts out of Vite's library mode. The downside is that we're not building a CommonJS-compatible bundle, and that we have to keep track of all external dependencies, but the upside is that the bundlers we use in the final apps should be a lot more intelligent about assets.
I also noticed that in the output, it was using a mix of `React.createElement` and the new `_jsx` runtime. This was due to svgr handling the JSX transformation itself, so I made sure it was opting in the new JSX runtime.
> Do not inline the assets in the built package

- src/components/Avatar/Avatar.tsx
- src/components/Avatar/useIdColorHash.ts
The hook naming and documentation drifted away from its actual implementation.
This brings it closer to what it actually does!
> Refactor useUsernameColor to useIdColorHash

- src/components/Avatar/Avatar.module.css
- src/components/Avatar/AvatarStack.stories.tsx
- src/components/Avatar/AvatarStack.test.tsx
- src/components/Avatar/AvatarStack.tsx
- src/components/Avatar/__snapshots__/AvatarStack.test.tsx.snap
For https://github.com/vector-im/compound/issues/145
> Rename component to AvatarStack

- src/components/ActionControl/ActionControl.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Form/Control.tsx
- src/components/Form/Controls/Password/Password.tsx
- src/components/Form/Field.tsx
- src/components/Form/Label.tsx
- src/components/Form/Message.tsx
- src/components/Form/Root.tsx
- src/components/Link/Link.tsx
- src/components/Radio/Radio.tsx
- src/components/Toggle/Toggle.tsx
This makes it so that most components properly forward their ref to the underlying DOM node.
I needed this on the Form.Root element mostly, to be able to clear it, but I extended it to most interactive components.
One notable exception is the `<Button>` component (and therefore the `<Form.Submit>` component), because it is a mess to type correctly because of the generic type on it
> Forward refs to most components

- babel.config.cjs
- package.json
- src/components/ActionControl/ActionControl.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Form/Control.tsx
- src/components/Form/Controls/MFA/MFA.tsx
- src/components/Form/Controls/Password/Password.tsx
- src/components/Form/Field.tsx
- src/components/Form/Label.tsx
- src/components/Form/Message.tsx
- src/components/Form/Root.tsx
- src/components/Link/Link.tsx
- src/components/Radio/Radio.tsx
- src/components/Toggle/Toggle.tsx
- vite.config.ts
- yarn.lock
- in case we're building with the jsx-dev-runtime, it doesn't get included anymore
- react-dom/server doesn't get included anymore
- ensure we're not relying on babel
- make sure we're not using the React default export in the resulting bundle
> Clean up the build

- package.json
- src/components/Avatar/Avatar.test.tsx
- src/utils/string.ts
- vite.config.ts
- yarn.lock
I had a problem with consuming the ESM module in vitest.
The resulting bundle had a `import { split } from "lodash"`, which does not work because lodash is not an ESM module.
There is an alternative `lodash-es` which is an ESM module, but then using that would break some CJS environments.
`lodash`'s split function notably doesn't handle well some emoji graphemes, so instead this switches to `graphemer`
fixes vector-im/compound#196
> Switch to graphemer to split strings

- src/index.ts
Useful to help with consistency when using the Rich Text Editor.
It unfortunately does not use the Avatar react component, so we need to consume utils to make it consistent
> Export avatar utility functions

- .github/workflows/npm_release.yml
@Half-Shot This should give us tagged releases like in https://github.com/matrix-org/eslint-plugin-matrix-org/releases 
Would that be enough for what you're trying to achieve?
> Add NPM release CI workflow

- src/components/Avatar/Avatar.module.css
- src/components/Avatar/Avatar.tsx
- src/utils/SuspenseImg.tsx
For https://github.com/vector-im/compound/issues/137
Figma link: https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=522-742&mode=design&t=jsFgnt5eA33BaiFu-11
FAO @callumu 
<table>
<tr>
<td><h3> 🤮 Before
<td><h3> 💅 After
<tr>
<td>
<td> 
</table>
-----
It also makes proper use of `forwardRef` as it is needed in certain implementation, and can now receive all HTML Span attributes as props to give more flexibility, particularly on the accessibility side of things
> Update Avatar to new design spec

- src/components/Avatar/Avatar.module.css
- src/components/Avatar/Avatar.stories.tsx
- src/components/Avatar/Avatar.tsx
- src/utils/SuspenseImg.tsx
For https://github.com/matrix-org/matrix-react-sdk/pull/11393 and https://github.com/vector-im/compound/issues/137
Makes the button polymorphic and allows it to be a `button` as well as a normal Avatar.
The image now can load lazily as well.
And we have an improved Storybook story.
> Improvements to the Avatar component

- src/utils/string.ts
To work around https://github.com/flmnt/graphemer/issues/11
This will fix the failing jest tests in https://github.com/matrix-org/matrix-react-sdk/pull/11393
Runtime works because it is using the ESM module.
Thank you @sandhose for the pointer 🙇
> Add interoperability for graphemer import

- src/components/Avatar/Avatar.test.tsx
- src/components/Avatar/Avatar.tsx
- src/utils/SuspenseImg.tsx
It creates a lot more problems than it solves on the testing side of things on downstream projects.
We should instead strive to provide UI elements and leave individual products to make their fallback strategies
> Remove React.Suspense from Avatar

- src/components/Avatar/Avatar.tsx
- src/components/IconButton/IconButton.module.css
Fixes https://github.com/vector-im/element-web/issues/26055
- Remove hover state of disabled icon buttons
- Remove ID as the title of the avatar component by default
> Bugfixes for Avatar and IconButton components

- src/components/Avatar/Avatar.tsx
- src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
Before https://github.com/vector-im/compound-web/pull/66 `title={id}` was set on both the `button/span` and the `img` - this is super confusing for the accessibility tree. Then that PR changed the `title` on `img` to be `title` which made more sense but still set `title={id}` on the `span/button`.
Title should not be forced like this is and should be driven by the consumer, as if it already is used with a rich tooltip library then you don't want to double-up the title. Instead specifying the aria-label defaulting to id to provide a sensible name in the accessibility tree is used
For https://github.com/vector-im/element-web/issues/26055
> Fix Avatar's `title` & `aria-label` behaviour

- src/components/Button/Button.module.css
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
- src/components/Button/__snapshots__/Button.test.tsx.snap
Buttons in Compound have an optional slot for an icon to go in - this adds that capability to the Button component.
> Support icons on buttons

- src/index.ts
Surely you shouldn't have to manually import it from src/ in downstream projects?
> Include global.css in the build output

- src/components/Button/Button.module.css
Because of #72, the inner text of the button became left-aligned.
Before, it was center-aligned, which was important if the button was bigger than its natural size.
This fixes that.
Before:
After:
No changes when the button size is its natural one:
For the record, this affects MAS' pagination buttons:
> Fix a regression in the button alignment

- src/components/Avatar/Avatar.stories.tsx
- src/components/Avatar/AvatarStack.test.tsx
- src/components/Avatar/__snapshots__/AvatarStack.test.tsx.snap
The tests were just wrong. The test files were not typechecking correctly, which apparently we don't do as part of linting?
> Fix the AvatarStack component tests

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
This was an issue for MAS, where we need the ref to autofocus some buttons.
I had to do weird type assertions because of the generic `as` property, but the type looks correct, and the ref is properly forwarded.
> Forward the ref in the Button component

- src/components/ActionControl/ActionControl.tsx
- src/utils/useId.ts
Inspired by https://github.com/ezcater/recipe/blob/dc253df74f0b9c509f13172980eb8c1a0defb62a/packages/recipe/src/utils/hooks/useUniqueId.ts.
Fixes: vector-im/compound#224
Replaces: https://github.com/vector-im/compound-web/pull/85
> Ponyfill useId

- .eslintrc.cjs
- src/components/Search/Search.tsx
- src/utils/useId.ts
Looks like another case has slipped in since adding the ponyfill. So definitely good to prevent via eslint.
Fixes: vector-im/compound#228
> Prevent useId import from React and fix another occurrence

- .stylelintrc.json
- package.json
- src/components/Search/Search.module.css
- yarn.lock
I wasn't able to find a PostCSS plugin to automatically do this, but a lint rule is just as good IMO (and it has the advantage that we can bypass it if necessary).
Closes https://github.com/vector-im/compound/issues/220
> Add a lint rule for accidental hover states

- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.test.tsx
- src/components/Tooltip/Tooltip.tsx
Fixes https://github.com/vector-im/compound/issues/246
Following the discussion on https://github.com/vector-im/compound-web/pull/102
> Tooltip: rename shortcut to caption and styling fixes

- src/components/Tooltip/Tooltip.module.css
Caused by https://github.com/vector-im/compound-web/pull/103
> Fix class name mismatch in Tooltip

- .storybook/main.ts
- src/components/Alert/Alert.stories.tsx
- src/components/Avatar/Avatar.stories.tsx
- src/components/Avatar/AvatarStack.stories.tsx
- src/components/Button/Button.stories.tsx
- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Glass/Glass.stories.tsx
- src/components/IconButton/IconButton.stories.tsx
- src/components/Link/Link.stories.tsx
- src/components/MenuItem/MenuItem.stories.tsx
- src/components/MenuItem/ToggleMenuItem.stories.tsx
- src/components/Radio/Radio.stories.tsx
- src/components/Search/Search.stories.tsx
- src/components/Toggle/Toggle.stories.tsx
- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Typography/Heading.stories.tsx
- src/utils/__ComponentTemplate__/__ComponentTemplate__.stories.tsx
Various tweaks and improvements to storybook
- Set autodocs to the default behaviour (enabled where `tags` includes `autodocs`)
- Nest `AvatarStack` inside `Avatar` in story hierarchy
- Nest `IconButton` inside `Button` in story hierarchy
- Exclude the stories template from storybook build
- Add more variations to some stories
> Storybook: enable autodocs

- src/components/Button/Button.module.css
- src/components/Button/Button.tsx
- src/components/Button/__snapshots__/Button.test.tsx.snap
[Design specs](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=636-4&mode=dev)
Buttons have been updated in the design specs to use the same font and icon sizes in both the large and small variants.
> Update button styles

- src/utils/useId.ts
I'm still running into issues with `useId` on https://github.com/vector-im/element-web/pull/26229#issuecomment-1777065139. According to https://github.com/webpack/webpack/issues/14814, the only viable workaround appears to be making the usage unanalyzable. 🤷
> Make usage of useId unanalyzable

- package.json
- src/components/Separator/Separator.module.css
- src/components/Separator/Separator.stories.tsx
- src/components/Separator/Separator.test.tsx
- src/components/Separator/Separator.tsx
- src/components/Separator/__snapshots__/Separator.test.tsx.snap
- yarn.lock
Initially, we'll use it just for explicit/standalone `<hr>` elements.
There are no immediate plans to replace generic borders in components with standalone, nested divider elements.
> Create separator component

- src/utils/__ComponentTemplate__/__ComponentTemplate__.tsx
Fixes https://github.com/vector-im/compound/issues/252
Should be enforced with a rule https://github.com/vector-im/compound/issues/258
> Update gen component template to use forwardRef

- src/components/Alert/Alert.module.css
- src/components/Alert/Alert.stories.tsx
- src/components/Alert/Alert.test.tsx
- src/components/Alert/Alert.tsx
- src/components/Alert/__snapshots__/Alert.test.tsx.snap
https://github.com/vector-im/compound-web/assets/3055605/94565ce5-f995-49b8-8ee8-dfa7f0252485
Fixes https://github.com/vector-im/compound/issues/250
[Figma — Alert Component](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=795-7802&mode=design&t=UVgZk0pPlOaqkhma-0)
> Alert: add actions input

- package.json
The following syntax will set the style condition:
- CSS @import
- HTML <link rel="stylesheet">
> Add `style` package export for dist/style.css

- src/components/Typography/Heading.stories.tsx
- src/components/Typography/Heading.tsx
- src/components/Typography/Text.tsx
- src/components/Typography/Typography.tsx
Fix https://github.com/vector-im/compound/issues/271
- There is no `xs` size for heading in https://github.com/vector-im/compound-web/blob/main/src/components/Typography/Typography.module.css and https://github.com/vector-im/compound-design-tokens/blob/main/assets/web/css/cpd-common.css
- I excluded the `xs` size for the `Heading` component
- The `xl` size used in the [`H1` component](https://github.com/vector-im/compound-web/blob/main/src/components/Typography/Heading.tsx#L45) was not defined in the `Typography` component
- `xl` is not available for `Text/Body` component (https://github.com/vector-im/compound-web/blob/main/src/components/Typography/Typography.module.css)
TLDR: `xs` is only available for `Text/Body`. `xl` is only available for `Heading`.
> Fix `Typography` > `Heading` and `Text` size

- src/components/Typography/Heading.tsx
Small mistake on the html attribute used for the `H4` component.
> Fix `Typography` > `Heading` > `H4`

- src/components/Alert/__snapshots__/Alert.test.tsx.snap
- src/components/Badge/__snapshots__/Badge.test.tsx.snap
- src/components/Form/Controls/Text/Text.module.css
- src/components/Form/Controls/Text/Text.stories.tsx
- src/components/Form/Controls/Text/Text.test.tsx
- src/components/Form/Controls/Text/Text.tsx
- src/components/Form/Controls/Text/__snapshots__/Text.test.tsx.snap
- src/components/Menu/__snapshots__/DrawerMenu.test.tsx.snap
- src/components/Menu/__snapshots__/FloatingMenu.test.tsx.snap
- src/components/MenuItem/__snapshots__/MenuItem.test.tsx.snap
- src/components/MenuItem/__snapshots__/ToggleMenuItem.test.tsx.snap
- src/components/Typography/Text.stories.tsx
- src/components/Typography/Typography.module.css
- src/components/Typography/Typography.tsx
- src/components/Typography/__snapshots__/Heading.test.tsx.snap
- src/components/Typography/__snapshots__/Text.test.tsx.snap
- src/styles/global.css
For https://github.com/vector-im/element-web/issues/25538
Adds `disableLigatures` prop to `Form.Text`
Default behaviour is for ligatures to match the rest of typography, ie enabled.
See:
- https://57d2e811.compound-web.pages.dev/?path=/story/typography--ligatures
- https://57d2e811.compound-web.pages.dev/?path=/story/form-controls-text--filled
> Forms: make ligatures opt-in on inputs

- src/components/Menu/MenuItem.tsx
We really need to put a CI job in place to check our types against React 17 as long as we continue to support it, but for now let's fix this isolated type issue. (In React 17, undefined is not a valid return type for a functional component.)
> Make a return type compatible with React 17

- package.json
For some reason that I don't entirely understand, the conditional export here seems to upset postcss-loader (https://github.com/element-hq/element-web/issues/23595#issuecomment-1877670351) -- possibly because this is neither a cjs nor an es6 import. Since both `require` and `import` point to the same file, we might as well make it unconditional.
> Avoid conditional export for `./dist/style.css`

- src/components/Tooltip/Tooltip.tsx
Since there is [another breaking change to tooltips planned](https://github.com/element-hq/compound-web/pull/137), this is a good opportunity to clean up this deprecated prop.
> Tooltip: Remove deprecated 'shortcut' prop

- src/components/Form/Controls/Action/Action.stories.tsx
- src/components/Form/Controls/Action/Action.test.tsx
- src/components/Form/Controls/Password/Password.stories.tsx
- src/components/Form/Controls/Password/Password.test.tsx
- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/TooltipProvider.tsx
- src/index.ts
Rather than instantiating a separate provider for each tooltip, which prevents tooltips from sharing interaction state and hurts performance. (This is a breaking change!)
Closes https://github.com/element-hq/compound/issues/234
> Require a global tooltip provider

- package.json
- src/components/Menu/MenuItem.stories.tsx
- src/components/Menu/MenuItem.test.tsx
- src/components/Menu/MenuItem.tsx
- src/components/Menu/__snapshots__/MenuItem.test.tsx.snap
- yarn.lock
This PR allows to use a custom component as an `Icon` in the `MenuItem`.
For example, a nice teal rectangle:
> `Icon` in `MenuItem` can be a `ReactNode`

- src/components/Button/Button.module.css
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
- src/components/Button/__snapshots__/Button.test.tsx.snap
This implements the new destructive variants added to the button component in [Figma](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?node-id=637%3A1963&mode=dev), and brings some of the other spacing and color values in line with the specs.
Closes https://github.com/element-hq/compound/issues/300
> Improvements to Button

- src/components/Avatar/Avatar.module.css
They were inheriting the font-family value and therefore could end up displaying their initials in the browser's default font (as can be seen in Element Web, in a couple spots).
> Ensure that avatars use the correct font

- src/components/Button/UnstyledButton.tsx
- src/components/Menu/Menu.test.tsx
Menus open when a `keydown` or `pointerdown` event occurs on the trigger. Because we're using `aria-disabled` on our buttons to create an artificial disabled state, we're responsible for ensuring that those events are blocked.
> Don't allow disabled buttons to open menus

- src/components/Form/Controls/Action/Action.module.css
This is one of the weirdness of flexbox. See https://dfmcphee.com/flex-items-and-min-width-0/
Before: ([Storybook](https://compound-web.pages.dev/?path=/story/form-kitchen-sink--normal)) 
After: ([Storybook](https://quenting-action-input-min-wi.compound-web.pages.dev/?path=/story/form-kitchen-sink--normal))
> Fix the action input overflowing of small containers

- src/components/ReleaseAnnouncement/ReleaseAnnouncement.tsx
When not specifying the `JSX`import, the build uses this import `import("react/jsx-runtime").JSX.Element`
Built version
```ts
export declare function ReleaseAnnouncement({ 
/**
* The children anchor should be a single valid React element.
*/
children, placement, ...props }: PropsWithChildren<ReleaseAnnouncementProps>): import("react/jsx-runtime").JSX.Element;
export {};
```
But in react 17, `JSX` is not available in `import("react/jsx-runtime")`
https://github.com/matrix-org/matrix-react-sdk/actions/runs/8540097333/job/23396360882?pr=12380
`node_modules/@vector-im/compound-web/dist/components/ReleaseAnnouncement/ReleaseAnnouncement.d.ts(22,108): error TS2694: Namespace '"/home/runner/work/matrix-react-sdk/matrix-react-sdk/node_modules/@types/react/jsx-runtime"' has no exported member …
> Fix release announcement for react 17

- src/components/Tooltip/useTooltip.ts
Set the tooltip in controlled mode only when `open` is provided.
Call `onOpenChange` when provided.
During the react-sdk migration, I have case when the tooltip is in uncontrolled mode and a component is listening to the tooltip opening state
> Always call onOpenChange in Tooltip

- src/components/ReleaseAnnouncement/ReleaseAnnouncement.tsx
Add `aria-describedby` manually on the anchor.
The role of the RA is a `dialog` and not a `tooltip`, so `floating-ui` doesn't add this attribute.
I also removed a useless data-attribute. It was used in the floating ui example to show that we can have access to the some internal state but there is no use case for us.
> Release Announcement: fix accessibility issue on the anchor

- src/components/Avatar/Avatar.tsx
By omitting the `crossOrigin` attribute, we change avatars to use a non-CORS request to fetch the image. This allows avatars to load even on null origins (fixing https://github.com/element-hq/element-web/issues/26491), but also prevents us from inspecting the image data in JavaScript, for example by using it in a canvas. We weren't doing that of course, so switching to the locked-down non-CORS mode should have no consequences.
Closes https://github.com/element-hq/compound/issues/293
> Fetch avatars without CORS

- src/components/Form/Controls/EditInPlace/EditInPlace.module.css
- src/components/Form/Controls/EditInPlace/EditInPlace.stories.tsx
- src/components/Form/Controls/EditInPlace/EditInPlace.tsx
A little pick-n-mix of small changes to the EditInPlace component. May be easier to review commit-by-commit (each commit explains what it does individually).
There will be a separate PR for the in-progress spinner as it involves adding the spinner component.
> Fixes for EditInPlace control

- package.json
- vite.config.ts
I wondered why updating compound exploded the number of dependencies in my lockfile, and this is why.
It also looks like new dependencies got added but not marked as external, so they ended up in the bundle.
> Fix dev dependencies and bundle size

- src/components/Form/Controls/EditInPlace/EditInPlace.stories.tsx
- src/components/Form/Controls/EditInPlace/EditInPlace.test.tsx
- src/components/Form/Controls/EditInPlace/EditInPlace.tsx
Since we also disable the box whilst saving, we need to pass it though explicitly.
> Allow EditInPlace component to be disabled

- .storybook/preview.css
- .storybook/preview.ts
This is to help review stories with the dark variant. It's only affecting the generated docs pages, not the individual stories
| Before | After |
| --- | --- |
| ![image](https://github.com/element-hq/compound-web/assets/1549952/993942cd-b6da-4c5f-a2d0-c82ebc6d9f99) | ![image](https://github.com/element-hq/compound-web/assets/1549952/a5244524-854a-46d3-8ad2-dac6336d5df6) |
> Set a default background color in storybook docs pages

- src/components/Form/Controls/EditInPlace/EditInPlace.stories.tsx
- src/components/Form/Controls/EditInPlace/EditInPlace.test.tsx
- src/components/Form/Controls/EditInPlace/EditInPlace.tsx
- src/components/Form/Controls/EditInPlace/__snapshots__/EditInPlace.test.tsx.snap
Radix forms is supposed to leverage native validation APIs.
This means that setting `required`, `type=email`, `minlength` on the input field should just work.
It already worked, but there was no way to set an error message.
This is because you're supposed to have `<Message match="...">` inside the field, to render the error message for each kind of error you'd expect.
This makes it so that `children` passed in the `<EditInPlace>` component are rendered within the `<Field>`, which lets us do something like:
```jsx
<EditInPlace type="email" required minLength={5} maxLength={100}>
<ErrorMessage match="valueMissing">This field is required</ErrorMessage>
<ErrorMessage match="typeMismatch">This field must be an email</ErrorMessage>
<ErrorMessage match="tooShort">This field must be at least 5 …
```
> EditInPlace: pass error messages as children to allow better messages

- package.json
- yarn.lock
Related to https://github.com/element-hq/element-web/issues/27651
Force the resolution `@radix-ui/react-id`. `@radix-ui/form` was using a different version than `@radix-ui/dropdown-menu` so we had two id counters. We can get rid of this resolution when will move to react 18, radix will use react built in id generator.
> Force `@radix-ui/react-id` resolution

- package.json
If consumers forget to update the design tokens, it will break stuff for them.
This makes sure consumers have recent enough design tokens.
> Update the minimum peer dependency for design tokens to 1.6.0

- package.json
- src/components/Form/Controls/EditInPlace/EditInPlace.test.tsx
- src/components/Form/Controls/EditInPlace/__snapshots__/EditInPlace.test.tsx.snap
- yarn.lock
Our test output has become pretty noisy and full of warnings about misuse of `act`. This fixes those warnings; see the commits.
> Fix test warnings

- package.json
- src/components/InlineSpinner/InlineSpinner.tsx
- yarn.lock
We can do this now that we're consuming the custom SVG components exported by the design tokens package.
Closes https://github.com/element-hq/compound-web/issues/192
> Allow setting a ref on InlineSpinner

- package.json
- src/components/Button/ActionButton.stories.tsx
- src/components/Form/Controls/Action/Action.stories.tsx
- src/components/Form/Controls/Action/Action.test.tsx
- src/components/Form/Controls/EditInPlace/EditInPlace.stories.tsx
- src/components/Form/Controls/EditInPlace/EditInPlace.test.tsx
- src/components/Form/Controls/Password/Password.stories.tsx
- src/components/Form/Controls/Password/Password.test.tsx
- src/components/Form/Form.stories.tsx
- src/components/Form/PasswordForm.stories.tsx
- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/TooltipProvider.tsx
- src/components/Tooltip/useTooltip.ts
- src/index.ts
- yarn.lock
To make it easier to browse through tooltips on neighboring elements, a common UX optimization is to allow the hover delay to be "warmed up", so that it goes to zero after the first hover. We used to have this before the tooltip component was rewritten.
[Screencast from 2024-08-02 12-41-01.webm](https://github.com/user-attachments/assets/17179250-7208-4811-8bd5-a812f3cac336)
This is a breaking change because consumers are now required to wrap their application in a \<TooltipProvider\> component once again. I thought it'd be nice to do this before the next release because https://github.com/element-hq/compound-web/pull/229 and https://github.com/element-hq/compound-web/pull/211 are already breaking.
> Bring back the tooltip warm-up period

- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.test.tsx
- src/components/Tooltip/Tooltip.tsx
The combination of tooltip labels and non-interactive triggers was problematic: The tooltip component would place the label on the span element that it creates, rather than your provided trigger element. If your trigger was an icon or image, then accessibility tooling would flag it as missing a label. You might try putting aria-hidden on the element, but then you would still end up with the label being on an element that lacks a role (which is illegal).
The solution I've implemented here is to move the aria-labelledby and aria-describedby attributes to the trigger.
> Allow tooltips to label non-interactive triggers

- src/components/Tooltip/Tooltip.tsx
Two problems when using union:
1. You can provide both a label and a description without typescript complaining.
2. [You can't do `const foo:TooltipProps["label"]` or `TooltipProps["description"]`](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#unions-with-common-fields).
> Use XOR for `TooltipProps`

- src/components/Tooltip/TooltipProvider.tsx
Currently you can't do:
```JSX
<TooltipProvider>
<div>
foo
</div>
<div>
bar
</div>
</TooltipProvider>
```
> Use better type for children in TooltipProvider

- src/components/Form/Controls/EditInPlace/__snapshots__/EditInPlace.test.tsx.snap
- src/components/Tooltip/Tooltip.test.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/useTooltip.ts
`aria-labelledby` [cannot be chained](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby#benefits_and_drawbacks). So, it's not good practice to be setting `aria-labelledby` on both the anchor and the tooltip element.
The basic issue that I believe initially motivated the chaining was to distinguish the caption from the main tooltip content (by setting both `aria-labelledby` and `aria-describedby` on the tooltip element), so that the caption would not be considered part of the anchor's accessible label. But this was never actually working. The only good solution seems to be setting `aria-labelledby` and `aria-describedby` on the anchor to point directly to the label and caption elements.
> Avoid chaining aria-labelledby on tooltips

- src/components/Tooltip/useTooltip.ts
The memoized label needs to be recomputed when the id changes
> Fix toolip not adding `aria-labelled-by` when using the `label` prop

- package.json
- vite.config.ts
Fixes element-hq/compound#318
This tells rollup/vite to preserve the file structure of the source directory instead of bundling everything into a single file.
This means that as a downstream package, you'll only import what you need, and the rest will be tree-shaken for you.
Compound itself is rather small, but it has a few dependencies that only a handful of components use.
This means that if you only import a few components, it will be much smaller as it won't include `@radix-ui/*` and `@floating-ui/*` stuff.
Here is the diff on a quick hello-world project bundle analysis, which just imports a `Button`:
Total gzipped size: 89.15kB
Total gzipped size: 46.60kB
---
In MAS, it means it can code-split way better, putting a lot of compound components out of the main bundle:
> Make sure the output can be treeshaked

- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/useTooltip.ts
To finally ween Element Web off its legacy tooltip solution
> Add ability to specify aria-live & aria-atomic on tooltips

- src/components/Tooltip/Tooltip.test.tsx
- src/components/Tooltip/useTooltip.ts
The current behavior on touchscreens is that tooltips will open as soon as you touch the trigger and remain open indefinitely due to focus and simulated hover. This feels unexpected, particularly on mobile.
The solution implemented here is to ignore non-visible focus and simulated hover events, and instead allow tooltips to be opened by long-pressing on the trigger. This matches the behavior of native tooltips on Android (though I don't know whether iOS has this same interaction pattern).
> Make tooltips more touchscreen-friendly

- src/components/Form/Controls/MFA/MFA.test.tsx
user-event calls act internally, so the test produces no warnings.
> Remove redundant act calls

- src/components/Dropdown/Dropdown.test.tsx
- src/components/Dropdown/Dropdown.tsx
Controlling the dropdown value via its props is often more convenient and enables the value to be changed without user interaction.
> Allow dropdown state to be controlled

- src/components/Menu/MenuItem.tsx
- src/components/Menu/ToggleMenuItem.tsx
`ToggleMenuItem` lacks the `onClick` handler. We can't for example prevent default this event.
> Add onClick handler for `ToggleMenuItem`

- src/components/Menu/MenuItem.tsx
This is embarrassing. 
I put `C` as generic of the `MouseEventHandler` which is obviously not an HTMLElement but a tag......
> fix(menu item): correct typing for onClick

- vite.config.ts
Vite v6's default is to use the package name, or build.lib.fileName if specified. We do the latter, and it ended up unhelpfully being `_name_.css`.
This puts the behaviour back as it was to creating 'style.css'.
> Specify CSS file name in vite options
