.storybook/main.ts, package.json, src/components/Button/Button.stories.tsx, src/components/Form/Form.stories.tsx, yarn.lock
Adds a design tab to the storybook stories for a quick reference of the implementation
=> Add storybook figma integration

src/components/Avatar/Avatar.module.css
Fixes https://github.com/vector-im/compound/issues/73
=> Replace avatar tokens with correct color mapping

src/components/ActionControl/ActionControl.tsx, src/components/Alert/Alert.tsx, src/components/Avatar/Avatar.tsx, src/components/Button/Button.tsx, src/components/Form/Control.tsx, src/components/Form/Controls/Password.tsx, src/components/Form/Field.tsx, src/components/Form/Label.tsx, src/components/Form/Message.tsx, src/components/Form/Root.tsx, src/components/Form/Submit.tsx, src/components/Form/ValidityState.tsx, src/utils/SuspenseImg.tsx
See https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=vector-im_compound-web&open=AYgGG3PS1OyCkqxY_3ZK
=> Use React.JSX instead of global JSX namespace

src/components/Form/Controls/MFA/MFA.module.css, src/components/Form/Controls/MFA/MFA.test.tsx, src/components/Form/Controls/MFA/MFA.tsx, src/components/Form/Controls/MFA/__snapshots__/MFA.test.tsx.snap, src/components/Form/Controls/MFA/index.ts, src/components/Form/Controls/Password/Password.test.tsx, src/components/Form/Controls/Password/Password.tsx, src/components/Form/Controls/Password/index.ts, src/components/Form/Form.stories.tsx, src/components/Form/form.module.css
[Figma reference](https://www.figma.com/file/HUysJAhv6cK6p1Pc81Fxaa/Matrix-Authentication-Service-(MAS)?type=design&node-id=94%3A24733&t=KimCCp0SggfWqaaI-1) 
For https://github.com/vector-im/compound/issues/127
=> Create MFA 6-digits component

.npmignore, tsconfig.json
By default, `npm pack` excludes everything that is in the `.gitignore`, which is not what we want, since we exclude the `dist/` directory in it.
Instead, this adds a `.npmignore` file, which takes precedence over the `.gitignore`, and includes exactly what we need for a good npm package:
- the built files in dist/
- "declaration maps" in dist/, so that "Go to definition" in IDEs lead to the source files
- the source files in src/
- the tsconfig, so that IDEs don't get confused when exploring the source
- it excludes test files, stories and snapshots
This can be tested by:
- running `yarn pack`
- use the resulting package like this:
```json
{
"dependencies": {
"@vector-im/compound-web": "file:../compound-web/vector-im-compound-web-v0.0.1.tgz"
}
}
```
<details><summary>Full file list …
=> Include the right files in the npm packaging process

src/components/Badge/Badge.module.css, src/components/Badge/Badge.stories.tsx, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx, src/components/Badge/__snapshots__/Badge.test.tsx.snap
For https://github.com/vector-im/compound/issues/146
Can accomodate an icon too
=> Create Badge component

res/_headers
=> Update ACAO again

src/components/ActionControl/ActionControl.tsx, src/components/Alert/Alert.tsx, src/components/Badge/Badge.tsx, src/components/Button/Button.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Form/Control.tsx, src/components/Form/Field.tsx, src/components/Form/Label.tsx, src/components/Form/Message.tsx, src/components/Form/Root.tsx, src/components/Form/Submit.tsx, src/components/Link/Link.tsx, src/components/Radio/Radio.tsx, src/components/Toggle/Toggle.tsx, src/components/Typography/Heading.tsx, src/components/Typography/Text.tsx, src/components/Typography/Typography.tsx
- ActionControl 
- Alert 
- Badge 
- Button 
- Checkbox 
- Link 
- Radio 
- Typography 
- Form
=> Add JSDoc comments for components

src/components/Button/Button.module.css
This changes the tokens used in the Button component with semantic ones, so that the different teams behave well
=> Button: use semantic tokens

src/index.ts
For some reason they were not exported
=> Export the Badge and the Checkbox components

src/index.ts
This appears to have been forgotten.
=> Export the Text component

src/components/Avatar/Avatar.module.css
For https://github.com/vector-im/compound/issues/215
=> Offset all direct children of avatar stack

src/components/Avatar/Avatar.module.css, src/components/Avatar/AvatarStack.tsx
For https://github.com/vector-im/element-web/issues/26209
=> Ensure that the avatar clip element doesn't affect page layout

src/components/Checkbox/Checkbox.module.css, src/components/Checkbox/Checkbox.stories.tsx
Fixes https://github.com/vector-im/compound/issues/225
=> Fix: disabled unchecked checkboxes appear checked

src/components/Toggle/Toggle.module.css
To better match the [current designs on Figma](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=119-248&mode=design&t=xC4PKSqudFSJ04Dt-0)
Closes https://github.com/vector-im/compound/issues/221
=> Minor updates to the toggle component

.stylelintrc.json, package.json, src/components/ActionControl/ActionControl.module.css, src/components/Avatar/Avatar.module.css, src/components/Checkbox/Checkbox.module.css, src/components/Form/Controls/MFA/MFA.module.css, src/components/IconButton/IconButton.module.css, src/components/Radio/Radio.module.css, src/components/Search/Search.module.css, src/components/Toggle/Toggle.module.css, src/styles/global.css, yarn.lock
This stylelint plugin even comes with an autofixer, so it was pretty quick to set up.
Closes https://github.com/vector-im/compound/issues/233
=> Enforce the use of logical CSS properties

sonar-project.properties
The quality gates should not fail in https://github.com/vector-im/compound-web/pull/108
=> Remove stories and tests from duplicated lines calculations

src/components/Avatar/Avatar.stories.tsx, src/components/Button/Button.stories.tsx, src/components/Form/Form.stories.tsx, src/components/MenuItem/ToggleMenuItem.stories.tsx, src/utils/__ComponentTemplate__/__ComponentTemplate__.stories.tsx
It does not work in newer Storybook versions
=> Remove Figma definitions in storyboook

.storybook/main.ts, package.json, yarn.lock
Adds a11y addon in dev builds.
=> Add @storybook/addon-a11y

src/components/Icon/IndicatorIcon/IndicatorIcon.module.css
=> Make the default dot on the indicator icon black

src/components/Form/Controls/Text/Text.tsx, src/components/Icon/IndicatorIcon/IndicatorIcon.tsx
About unused refs and unrecognized props.
=> Fix some React warnings

.storybook/main.ts, .storybook/preview.ts, package.json, yarn.lock
Following https://github.com/element-hq/compound-web/pull/123.
Extract only the addition of `storybook-addon-jsx` of the original PR.
=> Resurrect: Add `storybook-addon-jsx`

src/components/Tooltip/Tooltip.tsx
Same issue than https://github.com/element-hq/compound-web/pull/155 ....
=> Fix tooltip react 17 build

src/components/Form/Controls/Password/__snapshots__/Password.test.tsx.snap, src/components/Tooltip/useTooltip.ts
Fix e2e test failing in https://github.com/matrix-org/matrix-react-sdk/pull/12416
=> Fix tooltip display

src/components/Tooltip/Tooltip.tsx
Replace the revert https://github.com/element-hq/compound-web/pull/170
Fix the rendering issue.
=> Add missing deps to memo

src/components/Form/Controls/EditInPlace/EditInPlace.test.tsx, src/components/Form/Controls/EditInPlace/EditInPlace.tsx, src/components/Form/Controls/EditInPlace/__snapshots__/EditInPlace.test.tsx.snap
=> Make EditInPlace submit on enter

package.json, src/utils/string.ts, vite.config.ts
Alternative to https://github.com/element-hq/compound-web/pull/181
Thanks @cometkim for raising the inefficiencies of graphemer.
cc @sandhose
=> Switch from graphemer to Intl.Segmenter

src/components/InlineSpinner/InlineSpinner.tsx
Closes https://github.com/element-hq/compound-web/issues/187
=> InlineSpinner: fix forward ref

src/components/Nav/NavItem.tsx
Useful when you want to focus a particular navitem
=> Allow passing a ref into NavItem

README.md, sonar-project.properties
For https://github.com/element-hq/sre-internal/issues/3184
Since the project is new on SonarCloud, please check all settings are alright there too.
=> Update sonarcloud project key

src/components/Form/Message.tsx, src/components/InlineSpinner/index.ts, src/index.ts
`InlineSpinner` component is not exported.
=> Export `InlineSpinner`

src/components/Menu/MenuItem.tsx
MenuItem: correct typing for onClick
=> MenuItem: correct typing for onClick

README.md
Remove non accessible link from the top of the readme
=> Remove non accessible link from the top of the readme
